buttercup/buttercup-desktop

package.json

Fixing bug: #44 
Please merge after resolving this issue: https://github.com/buttercup-pw/buttercup-core/issues/35

Bumped up buttercup module version

---

source/resources/js/app/tools/dialog.js
source/resources/js/app/views/entry.js
source/resources/js/app/views/sidebar.js

Added delete confirmation dialog

---

source/resources/css/ui/entries-list.scss
source/resources/js/app/views/entries.js

Add animation that makes it more obvious when you're deleting an entry.

Add delete animation

---

source/app/app.js
source/app/config/menu.js
source/app/config/menu/app.js
source/app/config/menu/edit.js
source/app/config/menu/help.js
source/app/config/menu/view.js
source/app/config/menu/window.js
source/app/lib/platform.js
source/resources/css/ui/entries-list.scss

Menu improvements

---

source/app/app.js
source/resources/js/app/tools/generate.js
source/resources/js/app/views/entry.js

Increased password strength

---

package.json
source/resources/js/app/collections/entries.js
source/resources/js/app/views/entries.js
source/resources/js/config.js

size() function is a prototype of Backbone.Collection and the property passed to addEntries was not an instance of Backbone.Collection, although it looked like it. This fixes issue #60.
Other than that, implemented fuzzy search which displays better results, faster.

Fix a bug in addEntries function that was breaking the search, also implemented fuzzysearch

---

src/main/app.js

fix: create window if all windows are closed

---

app/index.html
src/main/app.js
src/renderer/index.js
src/renderer/redux/modules/workspace.js

feat(files): open files in buttercup

---

package.json
src/renderer/components/archive/entry-form.js
src/renderer/system/buttercup/groups.js
yarn.lock

Jan 3 fixes

---

src/renderer/components/archive/copyable.js
src/renderer/styles/copyable.scss
src/renderer/styles/entry-form.scss
src/renderer/styles/workspace.global.scss

Fixes #130
Fixes #131 
Fixes #133

Fix: field label and input arrangement

---

src/renderer/components/archive/copyable.js
src/renderer/components/button.js
src/renderer/index.js

Fix: copy entry password no longer overrides global copy

---

app/index.html
src/main/app.js
src/main/config/menu/file.js
src/main/lib/files.js
src/renderer/redux/modules/workspace.js

Fix window titles in Linux and Windows

---

src/renderer/components/archive/copyable.js

Make password selectable by mouse

---

app/package.json
package.json
src/main/app.js
src/renderer/redux/modules/files.js

Fix clicking on buttons on intro screen

---

src/renderer/components/generator.js
src/renderer/styles/file-opener.scss
src/renderer/styles/generator.scss
src/renderer/system/utils.js

Jan 18 fixes

---

.babelrc
.travis.yml
package.json
script/travis.sh
src/renderer/components/tree-view/index.js
src/renderer/components/tree-view/tree-label.js
src/renderer/containers/tree-view.js
src/renderer/redux/modules/groups.js
src/renderer/system/buttercup/groups.js

Add empty trash functionality

---

src/renderer/styles/search-field.scss

updated search-field color

---

src/renderer/components/tree-view/index.js
src/renderer/redux/modules/groups.js
src/renderer/system/buttercup/groups.js

Not familiar with buttercup's api, but it should works now.

Fix move group to root

---

app/package.json
package.json

The importer version wasn't changed in app manifest.
Fixes #170

Fix buttercup importer version on dist

---

src/renderer/components/archive/sort-button.js
src/renderer/components/column.js
src/renderer/components/tree-view/index.js
src/renderer/containers/tree-view.js
src/renderer/redux/modules/entries.js
src/renderer/redux/modules/groups.js
src/renderer/system/buttercup/groups.js
src/renderer/system/menu.js
src/renderer/system/utils.js

Sorting for groups

---

src/main/app.js

Add crash reporter to main process

---

src/renderer/components/file-manager/cells.js

Filename sanitization in cloud file manager

---

src/renderer/system/buttercup/archive.js

Merge archive contents when saving

---

package.json
yarn.lock

Thanks to @perry-mitchell, this PR:
+ Fixes #202 
+ Fixes #214 
Related PR: https://github.com/buttercup/buttercup-core/pull/149

Upgrade buttercup-core-web

---

src/renderer/components/archive/entries.js
src/renderer/system/buttercup/entries.js

Disable move to trash for entries in Trash

---

src/renderer/components/tree-view/tree-label.js

Show untitled for groups that don't have any titles

---

src/renderer/components/file-manager/manager.js

Fix Windows URL resolving issue in File Manager

---

src/renderer/system/shortcuts.js
src/renderer/system/utils.js

Clean clipboard after 15s

---

package.json
src/renderer/components/column.js
yarn.lock

This Fixes #227 and implements OSX-like scrollbars on non-osx systems.

Implement custom scrollbars

---

package.json
src/shared/actions/archives.js
yarn.lock

Better password error string

---

app/package.json
package.json
src/main/config/menu/file.js
src/main/lib/buttercup.js
src/main/lib/files.js
yarn.lock

Import from 1Password Archive

---

README.md

Add some more description around Buttercup's features.

Add features text

---

package.json
src/main/config/menu/help.js

Add new menu items for better information accessibility.

Add menu items in help

---

app/package.json
package.json
src/renderer/components/column.js
src/renderer/index.js
src/renderer/styles/column.scss

@perry-mitchell merging this on my own discretion since the production version is broken

Hotfix column content styling

---

src/shared/actions/groups.js

Fix empty trash dialog choice

---

src/renderer/components/archive/entries.js
src/renderer/system/menu.js
src/renderer/system/utils.js

Fixes #244 
Fixes #245 
Fixes #246

Add context menu for copying entry information

---

package.json
src/main/app.js
src/renderer/index.js
yarn.lock

Add handler for unhandled rejections

---

package.json
src/renderer/system/menu.js
src/renderer/system/shortcuts.js

Add copy username shortcut to keyboard

---

src/renderer/components/file-manager/manager.js

Fix broken path resolving

---

app/views/index.html

Fixes https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_html_01. This commit assumes that English is the only language supported as of now.

Accessibility - Fix violation of AX_HTML_01

---

src/renderer/components/archive/entries.js
src/renderer/containers/archive/entries.js
src/shared/selectors/index.js
src/shared/utils/collection.js

Disable add button in Trash group

---

src/shared/utils/collection.js

Fix deep find method

---

app/package.json
package.json

Fixes lastpass import issue - multiline CSV values. - Fixes #297

Update buttercup importer version

---

src/main/app.js
src/renderer/components/workspace.js
src/renderer/containers/workspace.js
src/renderer/index.js
src/renderer/styles/img/spinner.svg
src/renderer/system/dialog.js
src/shared/actions/archives.js
src/shared/actions/types.js
src/shared/actions/ui-state.js
src/shared/buttercup/archive.js
src/shared/buttercup/ipc-datasource.js
src/shared/buttercup/store.js
src/shared/reducers/index.js
src/shared/reducers/ui-state.js
src/shared/selectors.js

Fixes #329 
Fixes #219 
Fixes #221 
Fixes #35 
Fixes #261

High Priority 1

---

src/renderer/components/sidebar.js

Fix sidebar archive list spacing

---

package-lock.json
package.json
src/renderer/index.js

Fix Nextcloud 503 Error

---

src/main/menu.js
src/main/windows.js
src/shared/reducers/settings.js

#282 - Hide Windows Menubar

---

app/package-lock.json
package-lock.json
src/main/menu.js

Change "Condensed Sidebar" shortcut

---

app/package-lock.json
app/package.json
package-lock.json
package.json
src/main/actions.js

Only send analytics in production

---

app/package-lock.json
app/package.json
package-lock.json
package.json
src/main/app.js
src/main/menu.js

This PR fixes:
- Windows data loss #354 
- Auto hide menubar option was being shown to wrong OS #282

Update the way state is saved, fix menubar autohide

---

src/main/app.js

Fix the error on before quit

---

app/package.json
package-lock.json
package.json
src/main/lib/files.js

Create a new window on file double click

---

src/main/lib/updater.js
src/main/menu.js

Increase update frequency, improve menu items

---

package-lock.json
package.json
src/main/app.js
src/main/lib/queue.js
src/main/utils/window.js
src/renderer/components/saving-modal.js
src/renderer/components/workspace.js
src/renderer/containers/workspace.js
src/renderer/system/queue.js
src/shared/buttercup/archive.js
src/shared/buttercup/store.js
src/shared/utils/promise.js

Queuing Save Operations

---

app/package-lock.json
app/package.json
package-lock.json
package.json
src/main/actions.js
src/renderer/index.js
src/shared/buttercup/archive.js
src/shared/buttercup/groups.js
src/shared/buttercup/import.js
src/shared/buttercup/ipc-datasource.js
src/shared/buttercup/storage.js

Upgrade Buttercup, Remove Analytics, 32Bit Support

---

src/main/menu.js
src/main/windows.js
src/shared/reducers/settings.js

Fixes Issue #369 
changed label 'auto hide' to 'hide/show'.
added 'ctrl+shift+H' as accelerator.

added keyboard shortcut to toggle visibility of menu bar.

---

src/renderer/components/empty-view.js

Welcome screen text fix

---

app/package-lock.json
app/package.json
package.json
src/main/lib/updater.js

Fix network error

---

src/renderer/components/tree-view/tree-label-edit.js

fixed: #379 new group input focus-out handler

---

src/shared/buttercup/archive.js

@perry-mitchell @sallar Do you okay with this message?

Fixed #330: unlock archive dialog error message

---

app/package-lock.json
app/package.json
package-lock.json
package.json
src/main/lib/updater.js

Check for update fix

---

src/main/lib/window-manager.js

Silently fail when procedure is not available

---

package-lock.json
src/renderer/components/sidebar-item.js
src/renderer/components/sidebar.js
src/renderer/containers/sidebar.js
src/shared/actions/archives.js
src/shared/buttercup/archive.js

Archive locking

---

app/package-lock.json
app/package.json
config/webpack.config.production.js
package-lock.json
package.json

Field typing Hotfix

---

.babelrc
config/webpack.config.production.js
package.json
test/app.js

I tried several options and found out, that the **unused** flag must be set to **false**.
>unused (default: true) -- drop unreferenced functions and variables (simple direct variable assignments do not count as references unless set to "keep_assign")
**Source:** https://github.com/mishoo/UglifyJS2/tree/harmony#parse-options
**Issue:** #410

Reenable uglifyjs

---

package.json

There was a vulnerability (debug) that was patched in core, which should be updated.

Upgrade buttercup core (security)

---

src/renderer/components/tree-view/tree-label-edit.js

Fix whitespace issue when editing tree items

---

src/renderer/system/utils.js

Add https prefix to incomplete URL when opening in browser

---

locales/config.json
locales/pt-br/base.json

I'm sorry about the #467 
I didn't knew the "rebase" command and term in git (learned today) and when @sallar said, my mind mixed up. 
I've deleted mine old repository and forked again just to let things be as they're in the origin\master right now. 
**Sorry for the inconvenience and the delay**

Added Brazilian Portuguese (new Language)

---

src/renderer/components/archive/copyable.js
src/renderer/components/archive/entries.js
src/renderer/components/archive/entry-form.js
src/renderer/components/archive/entry-input.js
src/renderer/components/archive/entry.js
src/renderer/components/archive/search-field.js
src/renderer/components/file-manager/cells.js
src/renderer/components/file-manager/index.js
src/renderer/components/file-manager/manager.js
src/renderer/components/file-manager/sources/webdav.js
src/renderer/components/saving-modal.js
src/renderer/components/sidebar-item.js
src/renderer/components/sidebar.js
src/renderer/components/tree-view/index.js
src/renderer/components/tree-view/tree-label-edit.js
src/renderer/components/tree-view/tree-label.js
src/renderer/containers/root.js

Use PureComponent instead of Component #487

---

CONTRIBUTING.md

when clicked on this link  "not found page" viewed.

fix CONTRIBUTING.m

---

locales/en/base.json
locales/fa/base.json
package-lock.json
package.json
src/renderer/components/sidebar-item.js
src/renderer/components/sidebar.js
src/renderer/containers/sidebar.js
src/renderer/system/dialog.js
src/renderer/system/queue.js
src/shared/actions/archives.js
src/shared/buttercup/archive.js
src/shared/i18n/index.js

Change Password

---

src/main/lib/icon/IconFileStorage.js
src/main/lib/icon/iconographer.js

Change fetch response to buffer

---

.babelrc
package-lock.json
package.json
src/renderer/system/queue.js
src/shared/actions/entries.js
src/shared/buttercup/archive.js
src/shared/buttercup/entries.js

Use channel queue for icon downloads

---

package-lock.json
package.json
src/renderer/components/sidebar-item.js
src/renderer/components/sidebar.js
src/renderer/components/workspace.js
src/renderer/containers/sidebar.js
src/renderer/containers/workspace.js
src/renderer/index.js
src/shared/actions/archives.js
src/shared/actions/types.js
src/shared/buttercup/archive.js
src/shared/buttercup/store.js
src/shared/reducers/archives.js
src/shared/reducers/settings.js
src/shared/selectors.js

Sortable Sidebar, Improvements to Colors, Core Upgrade

---

package-lock.json
package.json

This should address #520, but let's test with the ello.co URI before closing it.

Update iconographer -> 0.7.1

---

locales/de/base.json

This PR adds missing translations.

Update german language

---

src/main/app.js
src/main/lib/queue.js
src/main/windows.js
src/renderer/components/saving-modal.js
src/renderer/components/workspace.js
src/renderer/containers/workspace.js
src/renderer/index.js
src/renderer/system/queue.js
src/shared/buttercup/archive.js
src/shared/reducers/ui-state.js

Fix Saving Issue

---

src/main/app.js
src/main/utils/argv.js

Fixes #544
This change is being tested in Windows. (see issue)

Make app single instance

---

app/package-lock.json
app/package.json
package-lock.json
package.json

Update buttercup-importer deps

---

src/renderer/components/tree-view/index.js

Fix disabled move to group menu item

---

locales/fr/base.json

Could you please @perry-mitchell or @sallar review this.  :)

Last Buttercup strings added and translated to FR (french)

---

README.md

Add instructions on how to install Buttercup on Windows with Chocolatey

Add chocolatey install instructions

---

locales/it/base.json

Hi, I've added new strings and modified some already translated words, mainly because they were ambiguous in the context.
For example, "cancel" is better translated to "annulla" than "cancella" (that means "delete").

New Italian strings + some edits

---

package-lock.json
package.json
src/shared/buttercup/archive.js

Update Core + Fix unlock bug

---

locales/en/base.json
locales/fa/base.json
src/renderer/components/archive/copyable.js
src/renderer/components/archive/entry-view.js
src/renderer/containers/archive/entry.js
src/shared/buttercup/entries.js
src/shared/selectors.js

Fix sorting issues for entry fields

---

.travis.yml
app/package-lock.json
app/package.json
appveyor.yml
package-lock.json
package.json

- Updates Electron to v3
- Adds 32bit support to all platforms except Mac

Add 32bit support

---

app/package-lock.json
app/package.json
package-lock.json
package.json
src/renderer/system/auth.js

Fix dropbox navigation issue

---

README.md
locales/config.json
locales/pl/base.json

Hey,
I've added a Polish translation to the project basing on the [Duch translations PR](https://github.com/buttercup/buttercup-desktop/pull/640).

Add Polish language

---

build/buttercup-desktop.desktop

Add StartupWMClass entry for .desktop

---

src/renderer/components/archive/archive-search.js

This PR solves this issue: https://github.com/buttercup/buttercup-desktop/issues/719
Fixes #719

Auto-Focus first search entry on input

---

locales/fr/base.json

Add french translation for "System"

Add french translation for "System"

---

locales/fr/base.json
locales/id/base.json
package-lock.json
src/shared/actions/entries.js

in response to https://github.com/buttercup/buttercup-desktop/pull/738
As @ph1p stated there was a bug when saving incomplete entries, when the parameter isSavingNewEntry was a necessary piece of the code. I added it again. My bad :[.

added isSavingNewEntry again to prevent a bug

---

README.md
locales/ca_es/base.json
locales/config.json

10 million speakers language. 
Native to: Andorra, France, Italy, Spain.

Added catalan locale

---

locales/cs/base.json
locales/de/base.json
locales/en/base.json
locales/es/base.json
locales/fa/base.json
locales/fi/base.json
locales/fr/base.json
locales/hu/base.json
locales/id/base.json
locales/it/base.json
locales/nl/base.json
locales/pl/base.json
locales/pt_br/base.json
locales/ru/base.json
locales/tr/base.json
locales/uk/base.json
src/renderer/components/archive/entry-input.js
test/gui/app.js

Hi guys!
This pull request adds a tool tip for the password generator feature. I've added translations for the supported languages as well. Please let me know if you'd like to see any changes!
Fixes #713 
Tool tip:
Language support:

Enhancement: Add a tool-tip for the password generator

---

locales/de/base.json

This PR adds some new translation keys for the german language.

Updated german translation

---

.travis.yml
package-lock.json
package.json
src/main/lib/buttercup.js
src/shared/buttercup/types.js

Added support for importing bitwarden json files. See issue buttercup/buttercup-importer#30 and pull request buttercup/buttercup-importer#38

Bitwarden importer

---

app/package.json
package-lock.json
package.json

Upgrade the importer lib, which fixes kdbx v4 - #796.

Upgrade bcup importer - fixes #796

---

README.md

Fix simple typo: similiar -> similar

---

.eslintrc
app/package-lock.json
app/package.json
package-lock.json
package.json
src/main/app.js

Set origin header for outgoing requests

---

package-lock.json
package.json

Update google oauth2 client - Fix auth flow when authcode encoded

---

locales/ca_es/base.json
locales/cs/base.json
locales/de/base.json
locales/en/base.json
locales/es/base.json
locales/fa/base.json
locales/fi/base.json
locales/fr/base.json
locales/hu/base.json
locales/id/base.json
locales/it/base.json
locales/ko/base.json
locales/nl/base.json
locales/pl/base.json
locales/pt_br/base.json
locales/ro/base.json
locales/ru/base.json
locales/tr/base.json
locales/uk/base.json
locales/zh_cn/base.json

Update view-changelog-for-v field for patch issue #837

Fix : Wrong version in help menu

---

src/main/app.js
src/shared/store/filter-store.js

Fix security regression caused by Redux

---

build/installer.nsh
package-lock.json
package.json
src/main/actions.js
src/main/app.js
src/main/menu.js
src/main/utils/window.js
src/renderer/system/auth.js
src/shared/buttercup/entries.js

Fix google drive auth

---

README.md
build/entitlements.plist
package-lock.json
package.json

@perry-mitchell the README was formatted by Prettier

Add Notarization

---

locales/cs/base.json
locales/id/base.json
src/main/tray.js
src/renderer/components/tree-view/index.js
src/renderer/containers/add-archive-button.js
src/renderer/containers/tree-view.js

Includes a fix for issue #871 and some missing prettier format
Fixes #871

Bugfix for issue 871 Error creating items in Trash (should be disabled

---

locales/ca_es/base.json
locales/es/base.json

Buttercup version v1.19.0
- new translations
- some fields fixed
I didn't found any active contributing guidelines, any change to do tell me please. Thanks for that awesome tool

update es & ca_es locales

---

src/renderer/components/archive/entry-form.js
src/renderer/components/archive/entry-input.js

This will add autoFocus when you want to add a new entry.

Add autoFocus to the form title field

---

app/package-lock.json
app/package.json
package-lock.json
package.json
src/shared/actions/entries.js
src/shared/buttercup/archive.js
src/shared/buttercup/entries.js
src/shared/buttercup/store.js

Fix search error

---

app/package-lock.json
app/package.json
package-lock.json
package.json

Fixes buttercup/buttercup-core#287

Update buttercup to fix enormous vaults

---

app/package-lock.json
app/package.json
package-lock.json
package.json

Sorry for making you feel inconvenient. It seems that my base is not from the latest buttercup upstream. So I create a new PR to ensure no conflicts.

Further submission with package-lock jsons for fixing #919

---

locales/ca_es/base.json
locales/cs/base.json
locales/de/base.json
locales/en/base.json
locales/es/base.json
locales/fa/base.json
locales/fi/base.json
locales/fr/base.json
locales/hu/base.json
locales/id/base.json
locales/it/base.json
locales/ko/base.json
locales/nl/base.json
locales/pl/base.json
locales/pt_br/base.json
locales/ro/base.json
locales/ru/base.json
locales/tr/base.json
locales/uk/base.json
locales/zh_cn/base.json
package-lock.json
package.json
src/renderer/components/archive/copyable.js
src/renderer/system/utils.js

This PR offers a possible solution to the #768 issue. It adds a button similar to the existing copy or reveal password buttons, as well as the contextual menu option.  It also adds translation in all available languages.
Fixes #768

#768 - Make fields with URL value clickable

---

locales/fr/base.json

Added missing translations.
Fix translation errors.

French language update

---

source/shared/i18n/translations/index.ts
source/shared/i18n/translations/pl.json

Polish translation

---

.prettierrc
package-lock.json
package.json
source/main/actions/appMenu.ts
source/main/services/buttercup.ts
source/main/services/import.ts
source/renderer/ipc.ts
source/shared/i18n/translations/en.json

Integrating Buttercup vault importer in v2.

Vault import

---

.github/workflows/test.yml
package-lock.json
package.json
test/integration/app.spec.js

Adds integration tests using Spectron.

Spectron integration tests

---

source/shared/i18n/translations/de.json

- fixed typo of translation "edit" in the menu bar from "bearbeiten" to "Bearbeiten"
- improved translation of some phrases because it sounds better in German

improved German translation

---

source/main/actions/connect.ts
source/main/ipc.ts
source/main/services/googleDrive.ts
source/main/services/init.ts
source/main/services/protocol.ts
source/renderer/actions/addVault.ts
source/renderer/components/AddVaultMenu.tsx
source/renderer/components/standalone/FileChooser.tsx
source/shared/symbols.ts
source/shared/types.ts

Fixes for Google Drive file name (#822) and Google Drive authentication renewal (#1001).
Fixes #822
Fixes #1001

Google Drive fixes

---

source/main/services/update.ts
source/renderer/services/notifications.tsx
source/renderer/services/update.ts

This fix stops the repeated update notifications: fixes #1008

Prevent repeated update notifications

---

source/main/actions/tray.ts
source/main/services/config.ts
source/main/services/windows.ts
source/shared/i18n/translations/en.json

Saves the latest window position to config so that the window opens in the same position each time. Includes a window-reposition button in the tray menu.
Closes #975

Window position: Memory

---

source/renderer/components/search/SearchModal.tsx

Re-select search term on new searches

---

package-lock.json
package.json
source/main/actions/attachments.ts
source/main/ipc.ts
source/main/services/buttercup.ts
source/renderer/actions/attachment.ts
source/renderer/actions/facade.ts
source/renderer/actions/link.ts
source/renderer/components/VaultEditor.tsx
source/renderer/components/standalone/UpdateDialog.tsx
source/renderer/hooks/attachments.ts
source/renderer/library/encoding.ts
source/renderer/state/vaults.ts
source/shared/i18n/translations/en.json
source/shared/symbols.ts

Attachments support for **Files** and **WebDAV**.
Closes #484.

Attachments

---

source/shared/i18n/translations/index.ts
source/shared/i18n/translations/it.json

I could translate in Italian evey part of the code that was available, but some strings weren't present in the translation file.
So i'm waiting for the complete version of the translation file.

Translated to italian

---

source/shared/i18n/translations/index.ts
source/shared/i18n/translations/ro.json

Full Romanian translation based on the current base file.

Add Romanian translation

---

source/shared/i18n/translations/fr.json

Missing items added to FR translation

---

source/renderer/components/PasswordPrompt.tsx

hide/show password when unlocking a vault

resolves buttercup/buttercup-desktop#1114

---

source/main/actions/remove.ts
source/main/ipc.ts
source/main/library/FileStorage.ts
source/main/services/backup.ts
source/main/services/buttercup.ts
source/main/services/config.ts
source/main/services/storage.ts
source/renderer/App.tsx
source/renderer/components/VaultSettingsDialog.tsx
source/renderer/components/navigation/VaultTabs.tsx
source/renderer/hooks/vault.ts
source/renderer/services/vaultSettings.ts
source/renderer/state/vaultSettings.ts
source/shared/i18n/translations/en.json
source/shared/symbols.ts
source/shared/types.ts

Adds local backup (closes #1048) via new local vault settings.

Vault settings + backup

---

package-lock.json
package.json
source/main/ipc.ts
source/main/library/sources.ts
source/main/services/buttercup.ts
source/main/services/format.ts
source/renderer/actions/format.ts
source/renderer/components/VaultSettingsDialog.tsx
source/renderer/components/standalone/GoogleReAuthDialog.tsx
source/renderer/hooks/vault.ts
source/renderer/state/vaultSettings.ts
source/shared/i18n/translations/en.json
source/shared/types.ts
test/main/library/sources.spec.js

Format conversion

---

source/shared/i18n/translations/index.ts

Add zh_cn to index

---

package-lock.json
package.json
source/main/ipc.ts
source/renderer/actions/saveVault.ts
source/shared/i18n/translations/de.json
source/shared/i18n/translations/en.json
source/shared/i18n/translations/zh_cn.json

Fixes Google Drive saving bug, introduced in v2.19.0.
Improves vault saving via format updates. Changes default format to B.

Saving and loading improvements, Google upload fix

---

source/shared/i18n/translations/fi.json

Hey,
I made and created a Finnish translation of fi.json. 
All translated, I hope it worked.
source/shared/i18n/translations/fi.json

New translation fi.json

---

source/shared/i18n/translations/index.ts
source/shared/i18n/translations/ja.json

Add japanese.
The i18n for buttercup/ui was already done by another actor.

I18n for japanese.

---

source/main/services/config.ts
source/main/services/windows.ts

Maximizing the desktop application window upon opening

Maximizing the desktop application window upon opening

---

source/shared/i18n/translations/fr.json

Update French translation

---

source/main/library/build.ts
source/renderer/services/init.ts
source/shared/i18n/trans.ts
source/shared/i18n/translations/fr.json

Add a call to the translation function of buttercup/ui in init.
Fixes issue #999

Add translation of buttercup/ui components

---

package-lock.json
package.json

Update buttercup - fix CVE-2023-41646

---

README.md
SECURITY.md
package-lock.json
package.json
source/main/actions/config.ts
source/main/index.ts
source/main/library/FileStorage.ts
source/main/library/build.ts
source/main/services/arguments.ts
source/main/services/config.ts
source/main/services/launch.ts
source/main/services/migration.ts
source/renderer/components/PreferencesDialog.tsx
source/shared/i18n/translations/en.json
source/shared/i18n/translations/fr.json
source/shared/symbols.ts
source/shared/types.ts
tsconfig.json
tsconfig.web.json

Improves the background/hidden launch capability by adding a third option: start hidden on boot/auto-launch. Shows immediately for user-execution.
Replaces auto-launch package with native setting.
Closes #1260

Upgrade background launch

---

package-lock.json
package.json
source/main/actions/appMenu.ts
source/main/library/build.ts
source/main/services/launch.ts

Fix auto launch for linux

---

source/main/services/arguments.ts
source/main/services/init.ts
source/main/services/launch.ts

Handle mac auto launch / hidden

---

source/shared/i18n/translations/index.ts

This pull request represents a significant step towards making our application more accessible to the Portuguese-speaking population. By add one more language, we aim to provide a more inclusive and user-friendly experience for all the users.

Add Portuguese Language Support

---

source/shared/i18n/translations/it.json

@perry-mitchell 
Please merge. Thanks.

Italian language update

---

package-lock.json
package.json
source/main/library/build.ts
source/main/services/browser/api.ts
source/main/services/browser/controllers/entries.ts
source/main/services/browser/middleware.ts
source/main/services/browser/models.ts
source/main/services/buttercup.ts
source/main/services/search.ts

Updates browser API.
Improves/expands entry search. Fixes vault lock/unlock calls.

Browser API final tweaks/fixes

---

source/main/library/build.ts
source/main/services/browser/controllers/vaults.ts
source/main/services/buttercup.ts

Provide facade/source names in API

---

package-lock.json
package.json
source/main/library/build.ts
source/renderer/actions/webdav.ts
source/renderer/library/fsInterface.ts

Support webdav auto-authentication between password/digest authentication schemes.
Fixes #1290

Update webdav - support auto auth

---

source/renderer/components/standalone/BiometricRegistrationDialog.tsx

Bugfix for: https://github.com/buttercup/buttercup-desktop/issues/1281

Fix biometric registration

---

source/renderer/components/PasswordPrompt.tsx
source/renderer/hooks/vault.ts

Show vault title in unlock prompt

---

source/shared/i18n/translations/it.json

@perry-mitchell 
Please merge. Thanks.

Update Italian language

---

source/renderer/components/PasswordPrompt.tsx
source/shared/i18n/translations/en.json
source/shared/i18n/translations/nl.json

- Add biometrics enabled text to i18n, to make it ready for translation
- Update Dutch language

Add biometrics enabled text to i18n

---

.github/workflows/build.yml
package.json

Build universal Mac (M1) dmg

---

source/shared/i18n/translations/index.ts
source/shared/i18n/translations/zh_tw.json

Add zh_tw Traditional Chinese translation

---

source/renderer/App.tsx
source/renderer/components/VaultEditor.tsx
source/renderer/components/vault/styles/vault-ui.sass

Fix light mode

---

source/renderer/components/vault/CreditCard.tsx
source/renderer/components/vault/EntryDetails.tsx
source/renderer/components/vault/styles/vault-ui.sass

Fixes the attachments UI in the new merged setup.

Fix attachments UI

---

source/renderer/actions/format.ts
source/renderer/components/vault/AddEntry.tsx
source/renderer/components/vault/EntryDetails.tsx
source/renderer/components/vault/GroupsList.tsx

Fixes #1368 - Broken translation key
Before:
After:

Fix broken translation key
