buttercup/buttercup-desktop

source/app/app.js
I thought I'd have a go at a simple implementation to cover https://github.com/buttercup-pw/buttercup/issues/45.
This adds the basics for OS X menus, which allows OS X users to copy and paste on fields and manage the window.
=> Added support for loading standard menu on OS X platform

source/app/app.js, source/app/events.js
The `window-all-closed` event will handle the reopening of the Intro window, instead of the Archive windo itself so we can have a gracefull shutdown when user hits CMD+Q(or clicks Quit from the menu).
=> separate the CMD+Q command from the user closing windows, resolves #29

source/resources/js/app/tools/dialog.js, source/resources/js/app/tools/generate.js, source/resources/js/app/views/entry.js, source/resources/js/app/views/sidebar.js
To avoid accidentally erasing passwords from generating a new password, a confirmation dialog box new pops up if the password box is already populating when generating a new password.
=> Add confirmation for password generation

src/renderer/styles/tree-view.global.scss
=> fix: hide arrow if group has no children

src/renderer/components/generator.js
Updating the length so it can be a minimum of 10 characters makes for some faster-typed passwords:
This is also inline with [NIST's recommended minimum length](https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/) of 8 characters.
The generated passwords are still quite secure, and can be more practical than the 20 char ones. This update just allows for more flexibility.
=> Change minimum length of generated passwords to 10 chars

.travis.yml, app/index.html, package.json, script/travis.sh, src/renderer/components/tree-view/index.js, src/renderer/containers/tree-view.js, src/renderer/styles/tree-view.global.scss, src/renderer/styles/workspace.global.scss, src/renderer/system/buttercup/groups.js, src/renderer/system/menu.js, test/app.js, yarn.lock
This PR adds:
+ moving groups to other groups by right clicking on them
+ moving groups to root by dragging to gaps between groups or by right clicking
+ font smoothing in the UI
Fixes #147
=> Move Groups to Root

src/renderer/components/archive/search-field.js, src/renderer/styles/search-field.scss
Search icon was using a unicode string which was not available on Windows.
Fixes #165
=> Fix Search icon on Windows

package.json
First of all, thanks for the great open-sourced project you made! 
As the author of the `sweetalert2` dependency, I suggest to bump it to the latest.
There's the only one breaking change in the major release 6.0.0: https://github.com/limonte/sweetalert2/releases/tag/v6.0.0
Otherwise, a lot of improvements and bug-fixed were made since `^5.3.8`.
Greets from Turku :) Keep on good work!
=> Bump sweetalert2 dependency to latest (6.6.0)

package.json, src/renderer/components/file-manager/sources/dropbox.js, src/renderer/components/file-manager/sources/webdav.js, src/renderer/system/dialog.js, yarn.lock
Fixes #206 where a WebDAV connection issue was being caused by our custom `Button` element from `buttercup-ui` package not having a `type` property, so without a `type`, the `type` is always "submit", which was causing the webdav connection form to submit (navigate) before the code had a chance to connect to Yandex. Because Yandex's servers are slow, the "navigate" action (from the form submit) was happening earlier than react had a chance to re-render (as a result of successful connection). 
This PR also adds a few error dialogs and Fixes #207
=> Fix WebDAV connection issue, better error handling

package.json, src/main/config/menu/edit.js, src/renderer/index.js, src/renderer/system/shortcuts.js, yarn.lock
Fixes #195 
As @lietu mentioned in #195, Chromium has a bug that prevents us from overriding global shortcuts like `Control+C` on Windows and Unix systems. To get around this, I have implemented an in-browser shortcut manager that fixes two issues:
+ Works on Windows and Linux
+ It doesn't override the native `Ctrl+C` behavior, so if anything else is selected in the window, it will be normally copied.
=> Global shortcut manager for archive window

package.json, src/main/config/menu/file.js, src/main/lib/buttercup.js, src/main/lib/files.js
Just enables the LastPass options from here: https://github.com/buttercup/buttercup-importer/pull/12
Should probably wait until a new version of `buttercup-importer` is published with https://github.com/buttercup/buttercup-importer/pull/12 so I can bump the `buttercup-importer` version in `package.json` before merging this.
=> Add LastPass import option

src/main/actions.js
This removes the update notice when the app starts, the reason is if the user hasn't clicked on the update notice to install the latest update and quits the app, the update automatically gets installed but the update notice is not immediately removed. 
Fixes #267
=> Remove update notice on restart

README.md
Only changed the link, but it seems that my Beautify removed some whitespace.
=> Change AUR link because of repo rename

src/main/actions.js, src/main/menu.js, src/shared/actions/archives.js, src/shared/buttercup/store.js
=> Fix menu bar update frequency

appveyor.yml
Added `appveyor-retry npm install` to build script. Temporarily handles #419.
=> Take that, appveyor!

locales/de.json, src/renderer/components/tree-view/index.js, src/shared/selectors.js
This PR fixes #421.
**Reproduce**
- create a root folder
- right click 
- move to root
- disappears
or
- only one root folder exists
- right click
- move to groups is empty
=> Fix root folder context menu

src/renderer/components/tree-view/index.js, src/shared/actions/groups.js
After two redbull and one line of code, I've fixed a bug in the treeview. 
**Reproduce:**
=> Fix expand bug in tree view

package.json
Hi! I put together this PR to add a [snap](https://snapcraft.io) package. I've tested it on Ubuntu 17.10 but it should work just as well on Ubuntu 14.04, 16.04, Linux Mint, Manjaro, Debian, OpenSUSE, Solus, etc.
If you merge and `npm run package:linux` it will create `release/buttercup-desktop_0.25.1_amd64.snap`.
Copy this to a Linux system, [enable snap support](https://docs.snapcraft.io/core/install), then run:
`sudo snap install --dangerous buttercup-desktop_0.25.1_amd64.snap`
Run with `buttercup-desktop` or find it in the launcher.
If you create a developer account and push this to the Snap Store, it can be discovered and installed through GNOME Software and https://snapcraft.io/discover. To create the developer account, [sign up here](https://dashboard.snapcraft.io/dev/account/), …
=> Add a snap package (https://snapcraft.io)

package.json, src/shared/utils/collection.js, src/shared/utils/test/collection.js, test/gui/app.js, test/unit/collection.js
This pull request contains the following change:
- Ignoring case when sorting items(+ tests for this change)
I wasn’t sure that where should I put unit tests for this method, so I have made a minor change in **ava** settings and put tests for this method under its parent folder. Please let me know if any changes required, especially in tests.
--
Fixes #476
=> Ignore case in sort methods

README.md
- Change link URL to a working URL path, as old link was pointing to a missing location.
=> fix(README.md) change to working URL

src/renderer/components/sidebar-item.js, src/renderer/system/shortcuts.js
A user can now hit `Ctrl+l` on windows/linux or `Command+l` on Mac to lock the current archive. 
Fixes #470
=> Added shortcut to lock current archive

src/main/windows.js, src/renderer/components/sidebar.js
Instead of having the title bar on macOS High Sierra (due to #339), we're opting for having the title bar but instead having no rounded corners.
=> Nicer frame for high sierra

package.json, src/renderer/components/sidebar-item.js
+ When trying to change the color of a locked archive, clicking on the color square caused the "click" event for the sidebar item to fire and unlock process to start.
+ Fix color contrast for light avatar items
+ Add lock state for locked items in condensed mode
+ Better color popover with custom colors
Fixes #325
=> Sidebar Icons Improvements

src/main/windows.js
**Problem**
Buttercup does not remember the last window position.
This PR should fix it.
I've tested this feature only on macos.
**Issue**
Fixes #535
=> Remember screen position (#535)

src/shared/actions/groups.js
I've found this strange behavior and fixed it by refreshing the group and its entries.
=> Fix empty trash bug

locales/fr/base.json
Hi @perry-mitchell & @sallar :)
I added two new translated strings to locales/fr/base.json
Like last time, there is an unbreakable space before the "!" caracter on the second string, which is normal and specific to French typographic rules.
Have a good day.
Best regards
Frederic
=> Added 2 recent EN to FR translated string

locales/fr/base.json
Hi @sallar, hi @perry-mitchell :)
Some adjustments to the French translation related to your recent modifications to the English one (manual installation).
As usual, the unbreakable space before "!" and "?" is perfectly normal according to the French typographic rules.
Best regards
Have a good day!
Frederic
=> FR locale - 1 new string, 2 modified

locales/fr/base.json
Hi @sallar, hi @perry-mitchell :)
thank you so much for the Export feature!!!
Here are some adjustments to the French translation related to the modifications you made to the English one since april.
As usual, the unbreakable space before "!" and "?" is perfectly normal according to the French typographic rules.
Best regards
Have a good day!
Frederic
=> FR Branch - 5 new translations

src/main/app.js
"operatios" v. operation ("operatios" sounds dope in pseudo-Latin though!)
=> fix(strings): before-quit log typo

src/shared/actions/entries.js
Hey! I fixed this issue #638
Now all folders and sub-folders should expand correctly.
fixes #638
=> Fix bug in global search form and expand all entry folders in tree-view

src/renderer/system/shortcuts.js
Hi! I've found a small error. This PR will fix it.
**Reproduce:**
- Start Buttercup
- Don't login to archive and do not select an entry
- Press CMD+B
**Screenshot:**
=> Fix shortcuts  and prevents errors when pressing cmd+b

locales/en/base.json, locales/fr/base.json, src/shared/actions/entries.js, src/shared/selectors.js
When creating a new entry, if a user click on an another entry to view
it, ask to him to confirm his action to prevent a data loss.
Update the onClick event on a list element (entries-list) to
be able to check the state of the app and display the dialog window
if it is needed. Create a redux selector to retrieve the mode field
to be able to check into the list if a new entry is opened.
Fixes: https://github.com/buttercup/buttercup-desktop/issues/634
=> feat: prevent loss of an unsaved entry.

src/renderer/components/archive/archive-search.js
To reproduce:
- Unlock an archive
- Use cmd+F
- Type "s["
__Buttercup v1.12.2__
=> fix: tolerate invalid RegExp patterns in archive search

README.md, locales/config.json, locales/fi/base.json
The Finnish (🇫🇮) locale to the Buttercup. Adds the locale also to the *readme* and *config.json* files.
[Mr. Bleadof](https://github.com/bleadof) checked that I didn't write any foolish translations.
=> Add finnish locale

src/renderer/components/file-manager/sources/webdav.js
Unescaped it according to [react-i18next docs](https://www.i18next.com/translation-function/interpolation#unescape).
The docs also mention
> Warning: If you toggle escaping off, you should escape any user input yourself!
Is this necessary in this case? And if so, how would we do that?
closes #728
=> Fix error message for webdav connection error

src/renderer/components/archive/entry-input.js
Right now it is really hard to toggle the password generator. You have to click the black part of the icon (not even the white background works). 
With this change, it is easier to toggle, since clicking the whole square will toggle the generator.
=> Make it easier to toggle generator

src/shared/actions/entries.js
Fixes #735 Now when clicking somewhere else during edit mode it will warn you of losing unsaved work. 
notes: I refactored some of the previous code because some of it seemed unnecessary like the parameter `isSavingNewEntry` which is always false and no code toggles it. I didn't understand the currentEntry check; I think checking the currentEntryMode will suffice.
=> Feature: Warn before losing unsaved entry (edit mode)

src/renderer/components/archive/copyable.js, src/renderer/system/utils.js
Before:
Password was being cleared for clipboard when user would enter ctrl-c, but not when the user pressed the button right of the password.
Now:
Password is cleared from the clipboard for both scenarios.
=> Issue626:  Users password is now cleared from the clipboard after a short duration

src/renderer/components/archive/copyable.js, src/renderer/system/shortcuts.js, src/renderer/system/utils.js
Two small changes around the clipboard behavior for passwords.
- 15s password clearing only applied if clipboard has not changed
- Concealed password can be copied directly
I think these changes should satisfy #774. The use of `clear` might even resolve #626 (though I don't have a windows machine to test this with)
Not sure about the use of `!important` on the style...
Let me know what you guys think!
Fixes #774
Fixes #626
=> Password clipboard behavior changes

locales/en/base.json, locales/fr/base.json, src/shared/buttercup/entries.js
when a user creates custom fields with the same label, an error
message has to be throw by the form validator. if not, the custom
field is erased and only the last one is saved.
update the entry form validation function to be able to return a form
error, when we have a duplicate custom field, declared in an entry.
this action invalid the entry and prevent an eventual data loss by
canceling the update action.
Fixes: https://github.com/buttercup/buttercup-desktop/issues/717
=> fix: display an error when an entry has duplicate custom fields

src/renderer/components/password-modal.js
Fixes: #874  
When opening a Buttercup archive with an incorrect password, the entered password is selected for easier re-entry.
=> Add select text for incorrect password input

.travis.yml
As the node version is not defined in `.travis.yml` anymore, should also remove it in the `$NAME` variable, in case the version was updated in the future but the name wasn't, which will be confusing.
=> Remove node.js version in TravisCI $NAME variable, cc #799

src/main/lib/files.js
when creating a new vault the user enter a name. Be sure to force the
new vault name with .bcup extension to be able to finalize the
archive creation (open the archive and create a password).
Fixes: https://github.com/buttercup/buttercup-desktop/issues/860
=> feat: force .bcup extension for new vault

src/renderer/components/password-modal.js, src/renderer/components/sidebar.js, src/renderer/components/workspace.js, src/renderer/containers/workspace.js
when opening an archive (on the sidebar), pass the item to active to
show to the user the selected item. Pass the archive name to the
password modal to display the archive name.
manage the selected archive from modalRequest state from the workspace and
pass the info to the sidebar to make it active. retrieve and pass the
name to the password modal to be able to display the archive name.
Fixes: #812
=> show vault's title on password modal

source/main/services/biometrics.ts
Fixed the crash due to `TypeError: electron_1.systemPreferences.canPromptTouchID is not a function` mentioned in #990 and likely also the cause of #993. 
Currently tested this on Manjaro Linux.
EDIT: Fixes #993
=> Fixed Biometrics Crash

package.json
Removes the AppImage artifact version from its filename, preventing the renaming of the AppImage after auto updating.
Fixes #1004
=> Remove appimage version

source/main/index.ts, source/main/services/arguments.ts, source/main/services/init.ts
This PR adds support for a new command line argument do prevent opening the window initially. This is especially useful for auto-starting the app daemon when the OS boots.
Specifying `--no-window` against the Buttercup executable will start the tray daemon but not open any main window.
Fixes #951
=> --no-window CL argument

README.md, package.json, source/main/index.ts
This MR adds some build config improvements around `AppImage` and protocol support. Protocol support is required for features like **Google Drive** to work.
Closes #1040
Closes #1037
=> Linux protocol bugfix

source/main/services/biometrics.ts
Fixes #1011.
Not sure if the error handling is correct, let me know if I should handle it differently (I figured a warning is enough).
=> fix(1011): search not working due to org.freedesktop.secrets missing

source/renderer/actions/unlockVault.ts
If we cannot open the vault with the password provided by the user, we now ask again for his vault password.
This aims at solving the issue #1065 
The new behavior for a wrong password is:
1. The user click on open a vault
2. He is asked for the vault password
3. He types the wrong password
4. The password prompt dialog closes, the processing gif is displayed, busy state, we attempt to unlock the vault
5. The vault unlock attempt finishes and results in a rejected promise
5. The busy state is set to false, the processing gif disappear and an error message is displayed
6. We ask again for the user vault password: the password prompt is opened again
Note that we will ask for the password again without knowing if it was a wrong password that caused the method …
=> Ask for password again when mistyped

package.json
I've tested the arm64 distribution and its working flawlessly. You can check out the binary at my fork. Resolves #1088
=> Added extra build targets for AppImage Distribution

source/main/services/init.ts, source/renderer/actions/facade.ts, source/renderer/actions/password.ts, source/renderer/actions/removeVault.ts, source/renderer/actions/unlockVault.ts, source/renderer/components/PasswordPrompt.tsx, source/renderer/components/VaultEditor.tsx, source/renderer/components/VaultManagement.tsx, source/renderer/components/VaultSettingsDialog.tsx, source/renderer/components/navigation/AutoNav.tsx, source/renderer/components/navigation/VaultTabs.tsx, source/renderer/components/search/SearchContext.tsx, source/renderer/components/standalone/BiometricRegistrationDialog.tsx, source/renderer/ipc.ts, source/renderer/services/facade.ts, source/renderer/state/password.ts, source/renderer/state/vaults.ts, source/shared/i18n/translations/en.json, source/shared/types.ts
Reworks the password prompt flow to be more intuitive, as it was not aging well. Fixes some bugs introduced in #1231.
=> Password prompt rebuild

README.md, package-lock.json, package.json, source/main/actions/config.ts, source/main/index.ts, source/main/services/config.ts, source/renderer/components/PreferencesDialog.tsx, source/shared/i18n/translations/en.json, source/shared/symbols.ts, source/shared/types.ts
Since Buttercup Desktop will be needed with Chrome's extension (manifest v3), users that were able to install the extension on their local account may end up being unable to install Buttercup Desktop if they don't have administrative privileges.
Adding oneClick:false and changing perMachine:false will launch an installation prompt giving the user a choice to install Buttercup per-user or per-machine (system wide).
Fixes [issue 1247](https://github.com/buttercup/buttercup-desktop/issues/1247)
Tested locally without any visible regression.
=> Modify NSIS options to allow installing Buttercup per-user

source/main/services/migration.ts
This fixes the `Layerr: Failed executing config migration: startInBackground: Cannot read properties of undefined (reading 'startInBackground')` error at startup for v2.24.x.
New to Buttercup here. The Buttercup app closed itself immediately at start, right after a clean (first) install. The error below showed up if I opened the app in a terminal.
```
[INF] 11:30:29: Application starting
[INF] 11:30:30: Application ready
[INF] 11:30:30: Application session started: 2023-12-16T11:30:30.182Z
[INF] 11:30:30: Logs location: C:\Users\USER\AppData\Local\Buttercup-nodejs\Log\buttercup-desktop.log
[INF] 11:30:30: Config location: C:\Users\USER\AppData\Roaming\Buttercup-nodejs\Config\desktop.config.json
[INF] 11:30:30: Vault config storage location: …
```
=> Fix undefined config preference during migration

source/main/services/googleDrive.ts, source/renderer/actions/addVault.ts, source/renderer/components/AddVaultMenu.tsx, source/renderer/components/standalone/GoogleReAuthDialog.tsx, source/renderer/services/authGoogle.ts, source/shared/i18n/translations/ca_es.json, source/shared/i18n/translations/de.json, source/shared/i18n/translations/en.json, source/shared/i18n/translations/es.json, source/shared/i18n/translations/fi.json, source/shared/i18n/translations/fr.json, source/shared/i18n/translations/it.json, source/shared/i18n/translations/ja.json, source/shared/i18n/translations/pl.json, source/shared/i18n/translations/pt-br.json, source/shared/i18n/translations/ro.json, source/shared/i18n/translations/zh_cn.json, source/shared/symbols.ts, source/shared/types.ts
Google has introduced increased restrictions and requirements for using open Drive permissions. This PR removes our requirement on our most permissive permissions scopes on Google Drive, requiring that Drive files are modified by Buttercup before being accessible.
=> Reduce google permissions requirement

package-lock.json, package.json, source/main/library/build.ts, source/main/services/config.ts, source/main/services/update.ts, source/renderer/components/PreferencesDialog.tsx, source/shared/i18n/trans.ts, source/shared/i18n/translations/ca_es.json, source/shared/i18n/translations/de.json, source/shared/i18n/translations/en.json, source/shared/i18n/translations/es.json, source/shared/i18n/translations/fi.json, source/shared/i18n/translations/fr.json, source/shared/i18n/translations/it.json, source/shared/i18n/translations/ja.json, source/shared/i18n/translations/nl.json, source/shared/i18n/translations/pl.json, source/shared/i18n/translations/pt-br.json, source/shared/i18n/translations/ro.json, source/shared/i18n/translations/zh_cn.json, source/shared/symbols.ts, source/shared/types.ts
Adds a pre-release channel setting for updates.
Resolves #1277.
Fixes #1269.
=> Pre-release channel support

README.md, source/main/ipc.ts, source/main/library/build.ts, source/main/services/arguments.ts, source/main/services/update.ts
Allow users to disable update checks via the CLI.
=> Disable updates via launch args

source/renderer/components/vault/GroupsList.tsx, source/renderer/components/vault/VaultContext.tsx
Hi 👋 
`parentGroupID` is not always mandatory specially when you create a group at the root of the vault
Closes: #1369
=> fix(groups): allow to create a group with no parent
